import { Platform, StyleSheet } from 'react-native';

// ─── Styles ──────────────────────────────────────────────────────────────────

export interface Palette {
  appBg: string; bg: string; card: string; panel: string; inset: string;
  border: string; borderStrong: string; accentBorder: string;
  text: string; text2: string; text3: string; muted: string; dim: string; dim2: string; placeholder: string;
  chipBg: string; chipText: string; chipBlueBg: string; chipBlueText: string;
  accent: string; accentBtn: string; link: string; linkSoft: string; overlay: string;
  // Status colors (theme-aware so they read well on both dark and light surfaces)
  successBg: string; success: string; dangerBg: string; danger: string; warnBg: string; warn: string;
  shadow: string; shadowOpacity: number;
}

export const DARK: Palette = {
  appBg: '#06080c', bg: '#0a0d12', card: '#111827', panel: '#0d1520', inset: '#1a2030',
  border: '#1e2a3a', borderStrong: '#2d3d50', accentBorder: '#1e3a5f',
  text: '#e8edf2', text2: '#c9d5e0', text3: '#8b97a6', muted: '#6b7a8e', dim: '#4b5a6e', dim2: '#3d4d5e', placeholder: '#4b5563',
  chipBg: '#1e2a3a', chipText: '#8b97a6', chipBlueBg: '#1e3a5f', chipBlueText: '#93c5fd',
  accent: '#3b82f6', accentBtn: '#1d4ed8', link: '#60a5fa', linkSoft: '#93c5fd', overlay: '#111827cc',
  successBg: '#064e3b', success: '#6ee7b7', dangerBg: '#450a0a', danger: '#fca5a5', warnBg: '#3b2f0a', warn: '#fbbf24',
  shadow: '#000000', shadowOpacity: 0.0,
};

export const LIGHT: Palette = {
  appBg: '#e5e8ec', bg: '#f5f7fa', card: '#ffffff', panel: '#f1f5f9', inset: '#e2e8f0',
  border: '#d8dee6', borderStrong: '#cbd5e1', accentBorder: '#bcd2f0',
  text: '#0f1722', text2: '#1f2937', text3: '#475569', muted: '#64748b', dim: '#94a3b8', dim2: '#94a3b8', placeholder: '#94a3b8',
  chipBg: '#e2e8f0', chipText: '#475569', chipBlueBg: '#dbeafe', chipBlueText: '#1d4ed8',
  accent: '#3b82f6', accentBtn: '#1d4ed8', link: '#1d4ed8', linkSoft: '#1d4ed8', overlay: '#ffffffcc',
  successBg: '#dcfce7', success: '#15803d', dangerBg: '#fee2e2', danger: '#b91c1c', warnBg: '#fef3c7', warn: '#b45309',
  shadow: '#0f172a', shadowOpacity: 0.07,
};

function makeStyles(c: Palette) {
  return StyleSheet.create({
    // On web/desktop, center the app as a phone-width column instead of stretching
    // edge-to-edge; on native it's a transparent full-screen passthrough.
    appShell: Platform.OS === 'web'
      ? { flex: 1, backgroundColor: c.appBg, alignItems: 'center' }
      : { flex: 1 },
    root: { flex: 1, width: '100%', maxWidth: Platform.OS === 'web' ? 480 : undefined, backgroundColor: c.bg },
    titleBar: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingTop: 6, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: c.inset },
    titleBarCompact: { paddingTop: 3, paddingBottom: 3 },
    headerLogo: { width: 26, height: 26, borderRadius: 6 },
    headerLogoSmall: { width: 13, height: 13, borderRadius: 3 },
    headerCompact: { fontSize: 14 },
    header: { color: c.text, fontSize: 20, fontWeight: '800', letterSpacing: 0.5 },
    headerTitleWrap: { flexDirection: 'row', alignItems: 'center', flexShrink: 1 },
    headerSub: { color: c.dim, fontSize: 11 },
    headerStatus: { flexDirection: 'row', alignItems: 'center', gap: 4, marginStart: 8 },
    statusDot: { width: 7, height: 7, borderRadius: 4 },
    statusDotWrap: { width: 10, height: 10, alignItems: 'center', justifyContent: 'center' },
    statusHalo: { position: 'absolute', width: 10, height: 10, borderRadius: 5 },
    statusCore: {
      width: 9, height: 9, borderRadius: 5,
      shadowOpacity: 0.9, shadowRadius: 4, shadowOffset: { width: 0, height: 0 }, elevation: 4,
    },
    headerFlag: { fontSize: 13 },
    headerRoleWrap: { marginStart: 'auto', flexDirection: 'row', alignItems: 'center', gap: 5 },
    headerRoleText: { color: c.text2, fontSize: 13, fontWeight: '700' },
    roleBtnInner: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    sectionTitle: { color: c.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.3, marginTop: 16, marginBottom: 4 },
    tabbar: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: c.inset, backgroundColor: c.bg },
    tab: { flex: 1, alignItems: 'center' },
    tabCompact: { paddingVertical: 6 },
    selectField: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: c.card, borderRadius: 8, borderWidth: 1, borderColor: c.border, paddingHorizontal: 12, paddingVertical: 12, marginTop: 4 },
    selectValue: { color: c.text, fontSize: 15 },
    selectOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 12 },
    selectOptionText: { color: c.text2, fontSize: 15 },
    selectOptionOn: { color: c.text, fontWeight: '700' },
    tabActive: { borderTopWidth: 2, borderTopColor: c.accent },
    tabText: { color: c.dim, fontSize: 11, textTransform: 'capitalize', marginTop: 2 },
    tabTextActive: { color: c.text, fontWeight: '600' },
    // Guided-tour coach-mark, anchored just above the tab bar (high zIndex so it
    // sits over the tab content). pointerEvents:box-none on the wrapper lets taps
    // pass through everywhere except the card itself.
    tourOverlay: { position: 'absolute', left: 0, right: 0, alignItems: 'center', paddingHorizontal: 16, zIndex: 50 },
    tourCard: { backgroundColor: c.card, borderRadius: 14, borderWidth: 1, borderColor: c.accentBorder, padding: 16, maxWidth: 420, width: '100%', shadowColor: '#000', shadowOpacity: 0.35, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 12 },
    tourCardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    tourStepIndicator: { color: c.text3, fontSize: 12, fontWeight: '600' },
    tourText: { color: c.text, fontSize: 15, lineHeight: 21 },
    tourBtnRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16 },
    tourSkip: { color: c.text3, fontSize: 14, fontWeight: '600' },
    tourNextBtn: { backgroundColor: c.accentBtn, borderRadius: 10, paddingVertical: 9, paddingHorizontal: 20, alignItems: 'center' },
    tourNextText: { color: 'white', fontWeight: '700', fontSize: 14 },
    // Closing note — a centered, full-screen card (not a tab pointer).
    tourFinalBackdrop: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: c.overlay, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, zIndex: 60 },
    tourFinalCard: { backgroundColor: c.card, borderRadius: 22, borderWidth: 1, borderColor: c.accentBorder, paddingVertical: 26, paddingHorizontal: 24, maxWidth: 380, width: '100%', alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.45, shadowRadius: 24, shadowOffset: { width: 0, height: 10 }, elevation: 18 },
    tourFinalLogo: { width: 60, height: 60, borderRadius: 15, marginBottom: 16 },
    tourFinalHead: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 12 },
    tourFinalKicker: { color: c.accent, fontSize: 13, fontWeight: '700', letterSpacing: 0.4, textTransform: 'uppercase' },
    tourFinalBody: { color: c.text2, fontSize: 15.5, lineHeight: 23, textAlign: 'center' },
    tourFinalWelcome: { color: c.text, fontSize: 19, fontWeight: '800', textAlign: 'center', marginTop: 18 },
    tourFinalBtn: { backgroundColor: c.accentBtn, borderRadius: 12, paddingVertical: 13, paddingHorizontal: 36, alignItems: 'center', marginTop: 22, alignSelf: 'stretch' },
    tourFinalBtnText: { color: 'white', fontWeight: '700', fontSize: 15.5 },
    badge: { position: 'absolute', top: -6, end: -12, backgroundColor: '#ef4444', borderRadius: 8, minWidth: 16, height: 16, paddingHorizontal: 3, alignItems: 'center', justifyContent: 'center' },
    badgeText: { color: 'white', fontSize: 10, fontWeight: '700' },
    card: { backgroundColor: c.card, marginHorizontal: 12, marginVertical: 8, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: c.border, shadowColor: c.shadow, shadowOpacity: c.shadowOpacity, shadowRadius: 8, shadowOffset: { width: 0, height: 2 }, elevation: c.shadowOpacity ? 2 : 0 },
    cardHighlight: { borderColor: c.accent },
    cardTitle: { color: c.text, fontWeight: '700', fontSize: 17, letterSpacing: -0.2, marginTop: 6, marginBottom: 4 },
    meta: { color: c.dim2, fontSize: 11, marginTop: 4 },
    dim: { color: c.dim, fontSize: 13, lineHeight: 19, marginTop: 4 },
    pad: { padding: 16, paddingBottom: 40 },
    label: { color: c.muted, fontSize: 12, marginTop: 12, marginBottom: 3, textTransform: 'uppercase', letterSpacing: 0.5 },
    fieldLabelRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
    charCount: { color: c.dim, fontSize: 11, marginBottom: 3 },
    input: { backgroundColor: c.card, color: c.text, borderRadius: 8, padding: 11, borderWidth: 1, borderColor: c.border, fontSize: 15 },
    mono: { color: c.link, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace', fontSize: 12, marginVertical: 8 },
    row: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
    rowLabel: { color: c.dim, fontSize: 12, width: 70 },
    rowValue: { color: c.text2, fontSize: 13, flex: 1 },
    btnRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    btnAccept: { backgroundColor: c.accentBtn, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
    btnCounter: { backgroundColor: '#065f46', borderRadius: 8, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
    btnDecline: { backgroundColor: '#374151', borderRadius: 8, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
    btnText: { color: 'white', fontWeight: '600', fontSize: 14 },
    // Button system for the negotiation row: one filled primary + ghost + text-danger
    btnGhost: { backgroundColor: 'transparent', borderWidth: 1, borderColor: c.accent, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
    btnGhostText: { color: c.accent, fontWeight: '600', fontSize: 14 },
    btnTextOnly: { paddingVertical: 10, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
    btnTextDanger: { color: c.danger, fontWeight: '600', fontSize: 14 },
    // Cautionary outline button (e.g. "incorrect plate/phone") — reads as a
    // warning, not a primary action.
    btnDangerOutline: { backgroundColor: c.dangerBg, borderWidth: 1, borderColor: c.danger, borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
    btnDangerOutlineText: { color: c.danger, fontWeight: '700', fontSize: 14 },
    inputFocused: { borderColor: c.accent },
    emptyWrap: { alignItems: 'center', justifyContent: 'center', paddingVertical: 48, paddingHorizontal: 24, gap: 10 },
    emptyText: { color: c.dim, fontSize: 14, textAlign: 'center' },
    priceTag: { color: c.text, fontSize: 16, fontWeight: '700', marginTop: 4 },
    roleGroupHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 8, paddingHorizontal: 2, borderRadius: 12 },
    roleGroupIcon: { width: 38, height: 38, borderRadius: 11, backgroundColor: c.chipBg, borderWidth: 1, borderColor: c.border, alignItems: 'center', justifyContent: 'center' },
    // Accent tint when the group is expanded — same hue in both themes.
    roleGroupIconOn: { backgroundColor: 'rgba(59,130,246,0.14)', borderColor: 'rgba(59,130,246,0.45)' },
    roleGroupLabel: { color: c.text2, fontSize: 12, fontWeight: '700', letterSpacing: 0.4, textTransform: 'uppercase' },
    roleGroupNote: { color: c.muted, fontSize: 12, marginTop: 1 },
    roleCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: c.card, borderRadius: 14, borderWidth: 1, borderColor: c.border, padding: 16 },
    roleCardOn: { borderColor: c.accent, backgroundColor: c.chipBlueBg },
    roleCardTitle: { color: c.text, fontSize: 16, fontWeight: '700' },
    roleCardDesc: { color: c.muted, fontSize: 13, marginTop: 2 },
    chip: { backgroundColor: c.chipBg, borderRadius: 6, paddingHorizontal: 9, paddingVertical: 4, fontSize: 12, color: c.chipText, marginEnd: 6, marginBottom: 4 },
    vehicleChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: c.chipBg, borderRadius: 6, paddingHorizontal: 9, paddingVertical: 4, marginEnd: 6, marginBottom: 4 },
    vehicleChipText: { fontSize: 12, color: c.chipText },
    distChip: { backgroundColor: c.chipBlueBg, color: c.chipBlueText },
    chipGreen: { backgroundColor: c.successBg, color: c.success },
    chipBlue: { backgroundColor: c.chipBlueBg, color: c.chipBlueText },
    chipRed: { backgroundColor: c.dangerBg, color: c.danger },
    chipYou: { backgroundColor: c.warnBg, color: c.warn },
    noteBox: { backgroundColor: c.panel, borderRadius: 8, padding: 10, marginTop: 8, borderWidth: 1, borderColor: c.border },
    noteLabel: { color: c.dim, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 },
    noteText: { color: c.text, fontSize: 14 },
    termsBox: { backgroundColor: c.panel, borderRadius: 8, padding: 10, marginTop: 8, borderWidth: 1, borderColor: c.border },
    termsTitle: { color: c.dim, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
    chatBox: { marginTop: 10, padding: 10, backgroundColor: c.panel, borderRadius: 10, borderWidth: 1, borderColor: c.border },
    chatTitle: { color: c.dim, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
    quickReplyChip: { paddingVertical: 7, paddingHorizontal: 12, borderRadius: 999, backgroundColor: c.card, borderWidth: 1, borderColor: c.border, maxWidth: '100%' },
    quickReplyChipText: { color: c.text2, fontSize: 13, fontWeight: '600' },
    chatExpand: { alignSelf: 'center', paddingVertical: 5, paddingHorizontal: 12, marginBottom: 4, borderRadius: 999, backgroundColor: c.card, borderWidth: 1, borderColor: c.border },
    chatExpandText: { color: c.accent, fontSize: 12, fontWeight: '600' },
    trackMsg: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    trackMsgText: { color: c.link, fontSize: 14, fontWeight: '600', textDecorationLine: 'underline' },
    // Outlined/secondary so it reads as a utility (open Maps) and never sits as a
    // second solid-blue block right above the primary "Picked up" action.
    navBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: c.card, borderWidth: 1, borderColor: c.accentBorder, borderRadius: 8, paddingVertical: 10, marginTop: 8, marginBottom: 8 },
    slideTrack: { height: 54, borderRadius: 12, backgroundColor: c.panel, borderWidth: 1, borderColor: c.accentBorder, justifyContent: 'center', alignItems: 'center', overflow: 'hidden', marginTop: 8 },
    slideLabel: { color: c.link, fontWeight: '700', fontSize: 15 },
    slideThumb: { position: 'absolute', left: 3, top: 3, bottom: 3, width: 54, borderRadius: 9, backgroundColor: c.accentBtn, alignItems: 'center', justifyContent: 'center' },
    navBtnText: { color: c.link, fontWeight: '700' },
    chatBubble: { maxWidth: '85%', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7, marginVertical: 3 },
    chatOut: { backgroundColor: c.accentBtn, alignSelf: 'flex-end' },
    // Card bg + border, NOT chipBg: light-mode chipBg (#e2e8f0) is nearly
    // identical to appBg (#e5e8ec), making inbound bubbles invisible on the
    // full-height chat surface (user report). Card contrasts on every
    // surface in both themes.
    chatIn: { backgroundColor: c.card, borderWidth: 1, borderColor: c.border, alignSelf: 'flex-start' },
    chatBubbleText: { fontSize: 14 },
    // Theme-aware per bubble: the "out" bubble is a dark-blue button in both
    // themes (light text); the "in" bubble is the chip background, so it must use
    // the theme text colour — otherwise a hardcoded light colour made the
    // incoming (e.g. Driver's) text invisible in light theme on native.
    chatTextOut: { color: '#f5f7fa' },
    chatTextIn: { color: c.text },
    dealBanner: { backgroundColor: c.successBg, borderRadius: 10, padding: 10, marginTop: 8 },
    pendingBanner: { backgroundColor: c.warnBg, borderRadius: 10, padding: 10, marginTop: 8 },
    pendingText: { color: c.warn, fontWeight: '700' },
    pendingSub: { color: c.warn, fontSize: 13, marginTop: 2, opacity: 0.9 },
    stageLine: { color: c.text2, fontSize: 13, fontWeight: '600', marginTop: 10, marginBottom: 6 },
    cancelLink: { color: c.danger, fontSize: 12, marginTop: 10, textAlign: 'center' },
    blockBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, alignSelf: 'center', paddingVertical: 6, paddingHorizontal: 10, marginTop: 6, marginBottom: 2 },
    blockBtnText: { color: c.danger, fontSize: 12, fontWeight: '600' },
    cancelBtn: { marginTop: 12, borderWidth: 1, borderColor: '#ef4444', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center', alignSelf: 'stretch' },
    cancelBtnText: { color: '#ef4444', fontWeight: '700', fontSize: 14 },
    cancelBox: { marginTop: 10, padding: 10, backgroundColor: c.panel, borderRadius: 8, borderWidth: 1, borderColor: c.accentBorder },
    cancelBoxText: { color: c.text2, fontSize: 13, marginTop: 8 },
    dealText: { color: c.success, fontWeight: '700' },
    dealContact: { color: c.success, fontSize: 13, marginTop: 2 },
    callLink: { color: c.link, textDecorationLine: 'underline' },
    callBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start', backgroundColor: c.accentBtn, borderRadius: 999, paddingVertical: 7, paddingHorizontal: 14, marginTop: 8 },
    callBtnText: { color: 'white', fontSize: 13, fontWeight: '600' },
    reportLink: { color: c.danger, fontSize: 12, fontWeight: '600' },
    reportReason: { flexDirection: 'row', alignItems: 'center', paddingVertical: 9 },
    reportReasonText: { color: c.text2, fontSize: 14, marginStart: 10 },
    radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1.5, borderColor: c.borderStrong, alignItems: 'center', justifyContent: 'center' },
    radioOn: { borderColor: c.accent },
    radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: c.accent },
    chatImage: { width: 160, height: 160, borderRadius: 8, marginVertical: 3 },
    imgViewerBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)' },
    imgViewerScroll: { flex: 1 },
    imgViewerContent: { flexGrow: 1, justifyContent: 'center', alignItems: 'center' },
    imgViewerImage: { width: '100%', height: '100%', flex: 1, alignSelf: 'stretch' },
    imgViewerClose: { position: 'absolute', top: 44, end: 20, width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
    chatAttach: { backgroundColor: c.chipBg, borderRadius: 8, paddingHorizontal: 12, justifyContent: 'center', alignItems: 'center', marginStart: 8 },
    chatAttachRec: { backgroundColor: c.danger },
    voiceMsg: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4, paddingHorizontal: 4 },
    voiceMsgText: { color: c.text, fontSize: 14, marginStart: 8 },
    addrBtn: { backgroundColor: c.card, borderWidth: 1, borderColor: c.border, borderRadius: 8, paddingHorizontal: 14, justifyContent: 'center', alignItems: 'center', marginStart: 8 },
    abRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: c.border },
    abText: { color: c.text2, fontSize: 14 },
    suggestBox: { marginTop: 4, backgroundColor: c.card, borderWidth: 1, borderColor: c.border, borderRadius: 8, overflow: 'hidden' },
    suggestRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 11 },
    suggestRowDiv: { borderTopWidth: 1, borderTopColor: c.border },
    suggestText: { color: c.text2, fontSize: 14, flex: 1 },
    counterBox: { marginTop: 12, padding: 12, backgroundColor: c.panel, borderRadius: 10, borderWidth: 1, borderColor: c.accentBorder },
    authorAvatar: { width: 22, height: 22, borderRadius: 11, backgroundColor: c.inset, marginEnd: 6 },
    authorName: { color: c.dim, fontSize: 12 },
    avatarRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
    statsRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, padding: 12, backgroundColor: c.panel, borderRadius: 10, borderWidth: 1, borderColor: c.border },
    statBox: { flex: 1, alignItems: 'center' },
    statValue: { color: c.text, fontSize: 14, fontWeight: '700' },
    statLabel: { color: c.dim, fontSize: 10, marginTop: 2, textAlign: 'center' },
    avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: c.inset },
    avatarEmpty: { alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.border, borderStyle: 'dashed' },
    avatarPlaceholder: { color: c.dim, fontSize: 28 },
    imageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    imageThumbWrap: { position: 'relative' },
    imageThumb: { width: 80, height: 80, borderRadius: 8, backgroundColor: c.inset },
    imageRemove: { position: 'absolute', top: -6, end: -6, backgroundColor: '#374151', borderRadius: 10, width: 20, height: 20, alignItems: 'center', justifyContent: 'center' },
    imageRemoveText: { color: 'white', fontSize: 10, fontWeight: '700' },
    imageAdd: { width: 80, height: 80, borderRadius: 8, borderWidth: 1, borderColor: c.border, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', backgroundColor: c.card },
    imageAddText: { color: c.dim, fontSize: 13, textAlign: 'center' },
    segRow: { flexDirection: 'row', marginTop: 8, borderRadius: 8, overflow: 'hidden', borderWidth: 1, borderColor: c.border },
    seg: { flex: 1, flexDirection: 'row', paddingVertical: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: c.card },
    segActive: { backgroundColor: c.chipBlueBg },
    segText: { color: c.dim, fontWeight: '600' },
    segTextActive: { color: c.chipBlueText },
    karmaLabel: { color: c.warn, fontSize: 11, marginStart: 6 },
    authorPhone: { color: c.dim, fontSize: 11, marginStart: 6 },
    authorVehicle: { color: c.text3, fontSize: 12, marginTop: 3 },
    waitTrack: { height: 3, borderRadius: 2, backgroundColor: c.inset, overflow: 'hidden', marginBottom: 8 },
    waitFill: { height: 3, borderRadius: 2, backgroundColor: c.accent },
    sysNotice: { flexDirection: 'row', gap: 10, marginHorizontal: 12, marginTop: 10, padding: 12, backgroundColor: c.panel, borderWidth: 1, borderColor: c.accentBorder, borderRadius: 12 },
    sysIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: c.inset, alignItems: 'center', justifyContent: 'center' },
    sysSender: { color: c.accent, fontWeight: '700', fontSize: 13 },
    sysText: { color: c.text2, fontSize: 13, marginTop: 2 },
    sysDetail: { color: c.text3, fontSize: 12, marginTop: 4 },
    repLine: { color: c.warn, fontSize: 11, marginTop: 3, marginStart: 28 },
    newBadge: { backgroundColor: c.warnBg, color: c.warn, fontSize: 10, borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1, marginStart: 6, overflow: 'hidden' },
    checkRow: { flexDirection: 'row', alignItems: 'center', marginTop: 14 },
    checkbox: { width: 20, height: 20, borderRadius: 4, borderWidth: 1, borderColor: c.borderStrong, backgroundColor: c.card, alignItems: 'center', justifyContent: 'center' },
    checkboxOn: { backgroundColor: c.accentBtn, borderColor: c.accent },
    checkboxTick: { color: 'white', fontSize: 12, fontWeight: '700' },
    checkLabel: { color: c.text2, fontSize: 13, marginStart: 8, flex: 1 },
    fieldError: { color: c.danger, fontSize: 12, marginTop: 4 },
    warnNote: { color: c.warn, fontSize: 12, marginTop: 6 },
    requiredBox: { backgroundColor: c.warnBg, borderRadius: 12, borderWidth: 1, borderColor: c.warn, padding: 12, marginBottom: 16, gap: 8 },
    requiredTitle: { color: c.warn, fontSize: 15, fontWeight: '800', marginBottom: 2 },
    requiredBtn: { backgroundColor: c.accentBtn, borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
    requiredBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
    requiredRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    requiredDismiss: { width: 38, alignSelf: 'stretch', borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: c.card, borderWidth: 1, borderColor: c.border },
    requiredDismissText: { color: c.text2, fontSize: 14, fontWeight: '700' },
    collapseHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 14, marginTop: 12, borderTopWidth: 1, borderTopColor: c.border },
    collapseLeft: { flexDirection: 'row', alignItems: 'center', flexShrink: 1 },
    collapseIcon: { marginEnd: 12, width: 22, textAlign: 'center' },
    collapseTitle: { color: c.text, fontSize: 18, fontWeight: '700', letterSpacing: 0.2 },
    searchBar: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingTop: 8, paddingBottom: 4 },
    searchInputWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: c.card, borderRadius: 8, borderWidth: 1, borderColor: c.border, paddingHorizontal: 10 },
    searchInput: { flex: 1, color: c.text, fontSize: 14, paddingVertical: 9 },
    sortBtn: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: c.panel, borderRadius: 8, borderWidth: 1, borderColor: c.accentBorder, paddingHorizontal: 10, paddingVertical: 9, maxWidth: 150 },
    sortBtnText: { color: c.linkSoft, fontSize: 12, fontWeight: '600', marginStart: 3 },
    sortBtnContent: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', flexShrink: 1 },
    sortChipItem: { flexDirection: 'row', alignItems: 'center' },
    sortBtnSep: { color: c.linkSoft, fontSize: 12, fontWeight: '600', marginHorizontal: 3 },
    catScroll: { flexGrow: 0, flexShrink: 0 },
    catRow: { paddingHorizontal: 12, paddingBottom: 6, gap: 8, flexDirection: 'row', alignItems: 'center' },
    catBack: { flexDirection: 'row', alignItems: 'center', gap: 2, backgroundColor: c.panel, borderRadius: 16, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: c.accentBorder },
    catBackText: { color: c.chipBlueText, fontSize: 12, fontWeight: '600' },
    catChip: { backgroundColor: c.card, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: c.border },
    catChipRow: { flexDirection: 'row', alignItems: 'center' },
    catChipIcon: { marginEnd: 5 },
    catChipOn: { backgroundColor: c.accentBtn, borderColor: c.accent },
    catChipText: { color: c.chipText, fontSize: 12 },
    catChipTextOn: { color: 'white', fontWeight: '600' },
    // On web the Modal overlays the whole browser window, not the 480px app
    // column — center the sheet and cap it to the column width so desktop
    // dropdowns don't stretch across the entire screen (user report).
    sortBackdrop: { flex: 1, backgroundColor: '#000000aa', justifyContent: 'flex-end', ...(Platform.OS === 'web' ? { alignItems: 'center' as const } : null) },
    sortSheet: { backgroundColor: c.bg, borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20, borderTopWidth: 1, borderColor: c.border, ...(Platform.OS === 'web' ? { width: '100%' as const, maxWidth: 480, borderLeftWidth: 1, borderRightWidth: 1 } : null) },
    sortChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
    sortChip: { backgroundColor: c.chipBg, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: c.borderStrong },
    sortChipRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    sortChipOn: { backgroundColor: c.accentBtn, borderColor: c.accent },
    sortChipText: { color: c.muted, fontSize: 13 },
    sortChipTextOn: { color: 'white', fontWeight: '600' },
    pinBtn: { backgroundColor: c.accentBtn, borderRadius: 8, paddingHorizontal: 14, justifyContent: 'center', alignItems: 'center', marginStart: 8 },
    pinnedHint: { color: c.success, fontSize: 12, marginTop: 4 },
    pinPrompt: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: c.accentBtn, borderRadius: 8, paddingVertical: 12, marginTop: 4 },
    pinPromptText: { color: 'white', fontWeight: '600', fontSize: 14 },
    mapModal: { flex: 1, backgroundColor: c.bg },
    mapModalBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: c.inset },
    mapModalTitle: { color: c.text, fontSize: 14, fontWeight: '600' },
    mapModalCancel: { color: c.text3, fontSize: 15 },
    mapModalDone: { color: c.link, fontSize: 15, fontWeight: '700' },
    mapCenterPin: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center', marginBottom: 40, zIndex: 1000, elevation: 1000 },
    mapLocating: { position: 'absolute', top: 16, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', backgroundColor: c.overlay, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8 },
    pickerBox: { backgroundColor: c.card, borderRadius: 8, borderWidth: 1, borderColor: c.border, marginTop: 4, overflow: 'hidden' },
    pickerField: { color: c.text, backgroundColor: c.card, borderWidth: 0, height: Platform.OS === 'ios' ? 150 : 52 },
    pickerItem: { color: c.text, fontSize: 16, height: 150 },
    toggleRow: { flexDirection: 'row', alignItems: 'center', marginTop: 16 },
    toggleTitle: { color: c.text, fontSize: 14, fontWeight: '600', marginBottom: 2 },
    switchTrack: { width: 46, height: 28, borderRadius: 14, backgroundColor: c.chipBg, padding: 3, justifyContent: 'center' },
    switchTrackOn: { backgroundColor: c.accentBtn },
    switchThumb: { width: 22, height: 22, borderRadius: 11, backgroundColor: c.muted },
    switchThumbOn: { backgroundColor: 'white', alignSelf: 'flex-end' },
    collapseChevron: { color: c.text3, fontSize: 18, fontWeight: '700' },
    map: { height: 160, borderRadius: 10, marginTop: 8, overflow: 'hidden' },
    timeBtn: { flex: 1, backgroundColor: c.card, borderRadius: 8, padding: 11, borderWidth: 1, borderColor: c.border, flexDirection: 'row', alignItems: 'baseline' },
    timeBtnText: { color: c.text, fontSize: 16, fontWeight: '600' },
    timeBtnHint: { color: c.dim, fontSize: 12, marginStart: 8 },
    stepBtn: { backgroundColor: c.chipBg, borderRadius: 8, paddingVertical: 11, paddingHorizontal: 14, marginStart: 8, alignItems: 'center', justifyContent: 'center' },
    stepBtnText: { color: c.chipBlueText, fontSize: 14, fontWeight: '700' },
    wheelRow: { flexDirection: 'row', backgroundColor: c.card, borderRadius: 8, borderWidth: 1, borderColor: c.border, overflow: 'hidden' },
    wheel: { flex: 1, color: c.text, backgroundColor: c.card, borderWidth: 0, height: Platform.OS === 'ios' ? 130 : 50 },
    wheelItem: { color: c.text, fontSize: 17, height: 130 },
    amountField: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginStart: 8 },
    amountSymbol: { color: c.text3, fontSize: 15, fontWeight: '700', marginEnd: 4 },
    amountInputInner: { color: c.text, fontSize: 15, textAlign: 'center', padding: 0, minWidth: 60 },
    curChip: { backgroundColor: c.card, borderRadius: 8, paddingVertical: 11, paddingHorizontal: 14, borderWidth: 1, borderColor: c.border, marginEnd: 8 },
    curChipActive: { backgroundColor: c.chipBlueBg, borderColor: c.accent },
    curChipText: { color: c.dim, fontSize: 14, fontWeight: '700' },
    curChipTextActive: { color: c.chipBlueText },
    amountInput: { flex: 1, marginStart: 8, textAlign: 'center' },
    // Amount readout + horizontal wheel picker
    // Bounded + centered so on wide (web/desktop) viewports the field underline
    // doesn't stretch full-width and push the "Amount" label off the left edge.
    // Hug content + center (do NOT set width:'100%' — with justifyContent center
    // that leaves free space the underlined field expands into, shoving the
    // "Amount" label and currency symbol out to the two edges). maxWidth caps it
    // on wide/desktop viewports; the value field shrinks if it ever overflows.
    amountReadout: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 6, alignSelf: 'center', maxWidth: 360 },
    amountReadoutLabel: { color: c.text3, fontSize: 13, fontWeight: '600', marginEnd: 8, flexShrink: 0 },
    amountReadoutField: { borderBottomWidth: 2, borderBottomColor: c.accentBorder, flexShrink: 1 },
    amountReadoutSym: { color: c.text3, fontSize: 20, fontWeight: '700', marginEnd: 6, flexShrink: 0 },
    amountReadoutInput: { color: c.text, fontSize: 30, fontWeight: '800', textAlign: 'center', padding: 0, minWidth: 80, letterSpacing: 0.5 },
    amountBtnRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
    amountBtn: { flex: 1, paddingVertical: 9, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: c.accentBorder, backgroundColor: c.panel, alignItems: 'center' },
    amountBtnText: { color: c.link, fontSize: 13, fontWeight: '600' },
    wheelWrap: { height: 60, marginTop: 6, justifyContent: 'flex-end' },
    wheelCell: { width: 14, alignItems: 'center', justifyContent: 'flex-end', height: 52 },
    wheelTick: { width: 2, height: 12, backgroundColor: c.dim, borderRadius: 1 },
    wheelTickMid: { height: 18, backgroundColor: c.text3 },
    wheelTickMajor: { width: 2.5, height: 26, backgroundColor: c.text2 },
    // Absolutely positioned + single-line so a label like "300k" overflows the
    // 14px tick cell (centered over the tick) instead of wrapping to two lines.
    wheelTickLabel: { position: 'absolute', top: 0, left: -19, width: 52, textAlign: 'center', color: c.text2, fontSize: 11, fontWeight: '700' },
    wheelCenter: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, alignItems: 'center', justifyContent: 'flex-end' },
    wheelCenterLine: { width: 3, height: 32, borderRadius: 2, backgroundColor: c.link },
    wheelCenterTri: { width: 0, height: 0, borderLeftWidth: 5, borderRightWidth: 5, borderTopWidth: 7, borderLeftColor: 'transparent', borderRightColor: 'transparent', borderTopColor: c.link, marginBottom: 1 },
    mapLink: { marginTop: 8, alignSelf: 'flex-start', backgroundColor: c.panel, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: c.accentBorder },
    mapLinkText: { color: c.link, fontSize: 12, fontWeight: '600' },
    codeBox: { marginTop: 10, backgroundColor: c.panel, borderRadius: 8, borderWidth: 1, borderColor: c.border, padding: 10 },
    codeText: { color: c.text2, fontSize: 12.5, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', lineHeight: 19 },
    link: { color: c.link, fontWeight: '600' },
    respondBtn: { marginTop: 10, backgroundColor: c.accentBtn, borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
    respondBtnText: { color: 'white', fontWeight: '600', fontSize: 14 },
    respondedText: { color: c.success, fontSize: 12, marginTop: 10, fontWeight: '600' },
    rateBtn: { marginTop: 8, alignSelf: 'flex-start', backgroundColor: c.chipBlueBg, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 6 },
    rateBtnText: { color: c.chipBlueText, fontSize: 12, fontWeight: '600' },
    ratedText: { color: c.dim, fontSize: 12, marginTop: 6 },
    karmaBtns: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    karmaBtn: { borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, backgroundColor: c.chipBg, borderWidth: 1, borderColor: c.borderStrong },
    karmaBtnActive: { backgroundColor: c.accentBtn, borderColor: c.accent },
    karmaBtnText: { color: c.muted, fontSize: 13 },
    karmaBtnTextActive: { color: 'white', fontWeight: '600' },
  });
}

export let s = makeStyles(DARK);
/** Active palette — for inline JSX colors (e.g. Picker.Item) that can't read `s`. */
export let palette: Palette = DARK;
/** Swap the active palette; caller must trigger a re-render afterwards. */
export function applyTheme(mode: 'dark' | 'light') {
  palette = mode === 'light' ? LIGHT : DARK;
  s = makeStyles(palette);
}
